language: python

matrix:
    include:
        - python: "2.7"
          env: TOXENV=py27
        - python: "pypy"
          env: TOXENV=pypy
        - python: "3.5"
          env: TOXENV=py35
        - python: "3.6"
          env: TOXENV=py36
        - python: "3.7"
          env: TOXENV=py37
        - python: "pypy3"
          env: TOXENV=pypy3
        - python: "3.8"
          env: TOXENV=py38
        - python: "3.9"
          env: TOXENV=py39

install:
  - pip install -U pip
  - pip install -U tox coverage

script:
  - tox

cache:
  pip: true
  directories:
    - eggs/
